theme: minima
title: Your awesome title
author: Corey Hampton
email: corey.hampton77@outlook.com
description: > # this means to ignore newlines until "baseurl:"
  I am not sure what to make this site about.

# social links
twitter_username: none # DO NOT include the @ character, or else the build will fail!
github_username:  CoreyHam # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage
